services:
  turismo-backend:
    build:
      context: ./
    container_name: turismo-backend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      proxy_network:
        aliases:
          - turismo-backend

networks:
  proxy_network:
    external: true
    name: proxy_network