"""Datos turísticos de Colima preparados para Wanderly.

Este archivo puede copiarse como ``app/seed.py``. Los campos ``source_data`` e
``image_credit_url`` se conservan como metadatos; el esquema SQLite actual los
ignora hasta que se agreguen sus columnas correspondientes.
"""

CONTENT = [
    {
        "slug":"volcan-de-fuego",
        "name":"Volcán de Fuego desde Suchitlán",
        "type":"Turismo",
        "municipality":"Comala",
        "active":True,
        "featured":True,
        "description":"Observa el volcán desde Suchitlán. Este punto de referencia no ofrece acceso al cráter.",
        "schedule":"Vista al aire libre · consulta avisos de Protección Civil",
        "lat":19.3745585,
        "lng":-103.7087398,
        "location_note":"El marcador corresponde al centro de Suchitlán, no a un mirador específico ni al cráter. Comprueba el punto de observación y las condiciones locales antes de salir.",
        "tags":["Naturaleza",
        "Aventura"],
        "image":"https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1000"
    },
    {
        "slug":"playa-la-boquita",
        "name":"Playa La Boquita",
        "type":"Turismo",
        "municipality":"Manzanillo",
        "active":True,
        "featured":True,
        "description":"Bahía tranquila, gastronomía local y atardeceres frente al Pacífico.",
        "schedule":"Abierto todo el día",
        "lat":19.1060124,
        "lng":-104.3988620,
        "tags":["Playa",
        "Gastronomía"],
        "image":"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/e4/83/f2/playa-la-boquita.jpg?w=1000"
    },
      {
        "slug":"museo-regional-historia",
        "name":"Museo Regional de Historia",
        "type":"Turismo",
        "municipality":"Colima",
        "active":True,
        "featured":False,
        "description":"Conoce la historia y las expresiones culturales de la región.",
        "schedule":"Horario de visita por confirmar",
        "lat":19.2427547,
        "lng":-103.7289773,
        "tags":["Cultura",
        "Museos"],
        "image":"https://images.unsplash.com/photo-1564399579883-451a5d44ec08?w=1000"
    },
    {
        "slug":"tianguis-villa-alvarez",
        "name":"Tianguis de la Villa",
        "type":"Tianguis",
        "municipality":"Villa de Álvarez",
        "active":True,
        "featured":False,
        "description":"Sabores, productos y encuentro comunitario en la avenida Josefa Ortiz de Domínguez.",
        "schedule":"Domingos · horario por confirmar",
        "lat":19.2668533,
        "lng":-103.7432098,
        "location_note":"El punto corresponde al tianguis registrado en la avenida Josefa Ortiz de Domínguez. Confirma que opere y su horario antes de visitarlo.",
        "tags":["Compras",
        "Gastronomía"],
        "image":"https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=1000"
    },
    {
        "slug":"tianguis-artesanal-comala",
        "name":"Tianguis artesanal de Comala (demo)",
        "type":"Tianguis",
        "municipality":"Comala",
        "active":True,
        "featured":False,
        "description":"Ejemplo de actividad artesanal de fechas variables; la sede del tianguis no está confirmada.",
        "schedule":"Fechas variables · por confirmar",
        "lat":19.3261439,
        "lng":-103.7554240,
        "location_note":"Contenido ilustrativo. El punto ubica la Casa de la Cultura de Comala como referencia, no una sede confirmada del tianguis.",
        "tags":["Artesanías"],
        "image":"https://unsplash.com/photos/a-red-and-yellow-building-with-a-mountain-in-the-background-Isb0cPo39Rs?w=1000"
    },
    {
        "slug":"mercado-obregon",
        "name":"Mercado Constitución",
        "type":"Mercados",
        "municipality":"Colima",
        "active":True,
        "featured":False,
        "description":"Un recorrido por los sabores cotidianos de la capital.",
        "schedule":"Horario de atención por confirmar",
        "lat":19.2402448,
        "lng":-103.7298978,
        "tags":["Gastronomía",
        "Compras"],
        "image":"https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=1000"
    },
    {
        "slug":"feria-cultura-colima",
        "name":"Festival de Cultura Colima (demo)",
        "type":"Eventos",
        "municipality":"Colima",
        "active":True,
        "featured":False,
        "description":"Ejemplo de evento cultural para demostrar los filtros; no existe cartelera confirmada.",
        "schedule":"Fecha de ejemplo: 18 oct 2026 · 18:00",
        "lat":19.2429725,
        "lng":-103.7297302,
        "location_note":"Evento ilustrativo. El punto muestra el Teatro Hidalgo como recinto de referencia; ni la sede ni la fecha están confirmadas para este festival.",
        "tags":["Cultura",
        "Familia"],
        "image":"https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1000"
    },

    
    {
        "slug": "comala-centro-historico",
        "name": "Centro histórico de Comala",
        "type": "Turismo",
        "municipality": "Comala",
        "active": True,
        "featured": True,
        "description": "Calles de fachadas blancas, portales y jardines en el corazón del Pueblo Mágico de Comala.",
        "schedule": "Todos los días · Espacio público; servicios y comercios con horarios propios",
        "lat": 19.3231443,
        "lng": -103.7582664,
        "location_note": "Centro, Comala, Colima",
        "tags": ["Cultura", "Pueblo Mágico", "Centro histórico"],
        "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/95/MaderoStreetComala1.jpg/1280px-MaderoStreetComala1.jpg",
        "source_data": "OpenStreetMap; Visita Colima",
        "image_credit_url": "https://commons.wikimedia.org/wiki/File:MaderoStreetComala1.jpg",
    },
    {
        "slug": "parroquia-san-miguel-comala",
        "name": "Parroquia de San Miguel Arcángel del Espíritu Santo",
        "type": "Turismo",
        "municipality": "Comala",
        "active": True,
        "featured": False,
        "description": "Templo emblemático situado frente al jardín principal de Comala.",
        "schedule": "Consultar antes de visitar · El acceso puede variar durante celebraciones religiosas",
        "lat": 19.3229762,
        "lng": -103.7580569,
        "location_note": "Calle Degollado, Centro, Comala, Colima",
        "tags": ["Cultura", "Arquitectura", "Religioso"],
        "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e3/MainChurchComala01.jpg/1280px-MainChurchComala01.jpg",
        "source_data": "OpenStreetMap; Visita Colima",
        "image_credit_url": "https://commons.wikimedia.org/wiki/File:MainChurchComala01.jpg",
    },
    {
        "slug": "museo-alejandro-rangel-nogueras",
        "name": "Museo Universitario Alejandro Rangel Hidalgo y Hacienda de Nogueras",
        "type": "Turismo",
        "municipality": "Comala",
        "active": True,
        "featured": False,
        "description": "Antigua hacienda vinculada con la obra del artista colimense Alejandro Rangel Hidalgo.",
        "schedule": "Consultar antes de visitar · Horario sujeto a la Universidad de Colima",
        "lat": 19.3234908,
        "lng": -103.7396034,
        "location_note": "Calle Hacienda Nogueras, Nogueras, Comala, Colima",
        "tags": ["Museos", "Arte", "Historia", "Arquitectura"],
        "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/36/MuseoUniversitarioRangel01.jpg/1280px-MuseoUniversitarioRangel01.jpg",
        "source_data": "OpenStreetMap; Universidad de Colima",
        "image_credit_url": "https://commons.wikimedia.org/wiki/File:MuseoUniversitarioRangel01.jpg",
    },
    {
        "slug": "laguna-la-maria",
        "name": "Laguna La María",
        "type": "Turismo",
        "municipality": "Comala",
        "active": True,
        "featured": False,
        "description": "Laguna rodeada de vegetación en las faldas del volcán, conocida por sus paisajes y actividades al aire libre.",
        "schedule": "Consultar antes de visitar · Confirmar acceso y condiciones del camino",
        "lat": 19.461445,
        "lng": -103.7095051,
        "location_note": "La Becerrera, Comala, Colima. El punto señala la laguna; confirma el acceso antes de viajar.",
        "tags": ["Naturaleza", "Laguna", "Ecoturismo"],
        "image": "https://upload.wikimedia.org/wikipedia/commons/d/dd/Vista_laguna_-_panoramio.jpg",
        "source_data": "OpenStreetMap; Visita Colima",
        "image_credit_url": "https://commons.wikimedia.org/wiki/File:Vista_laguna_-_panoramio.jpg",
    },
    {
        "slug": "suchitlan",
        "name": "Suchitlán",
        "type": "Turismo",
        "municipality": "Comala",
        "active": True,
        "featured": False,
        "description": "Comunidad de origen indígena reconocida por sus tradiciones, gastronomía, artesanías y entorno natural.",
        "schedule": "Todos los días · Comercios y espacios culturales con horarios propios",
        "lat": 19.3745585,
        "lng": -103.7087398,
        "location_note": "Suchitlán, Comala, Colima",
        "tags": ["Cultura", "Comunidad", "Gastronomía", "Artesanías"],
        "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a3/Suchitl%C3%A1n.JPG/1280px-Suchitl%C3%A1n.JPG",
        "source_data": "OpenStreetMap; Visita Colima",
        "image_credit_url": "https://commons.wikimedia.org/wiki/File:Suchitl%C3%A1n.JPG",
    },
    {
        "slug": "volcanes-desde-suchitlan",
        "name": "Vista de los volcanes desde Suchitlán",
        "type": "Turismo",
        "municipality": "Comala",
        "active": True,
        "featured": False,
        "description": "Punto de referencia en Suchitlán para observar a distancia los volcanes de Colima; no representa acceso al cráter.",
        "schedule": "Sujeto a condiciones meteorológicas · Consultar avisos de Protección Civil",
        "lat": 19.3745585,
        "lng": -103.7087398,
        "location_note": "Suchitlán, Comala, Colima. No acercarse a zonas restringidas ni interpretar el marcador como acceso al cráter.",
        "tags": ["Naturaleza", "Paisaje", "Volcán"],
        "image": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Volcanes_de_Colima_desde_Cofrad%C3%ADa_de_Suchitl%C3%A1n.jpg",
        "source_data": "OpenStreetMap; Protección Civil Colima",
        "image_credit_url": "https://commons.wikimedia.org/wiki/File:Volcanes_de_Colima_desde_Cofrad%C3%ADa_de_Suchitl%C3%A1n.jpg",
    },
    {
        "slug": "jardin-libertad",
        "name": "Jardín Libertad",
        "type": "Turismo",
        "municipality": "Colima",
        "active": True,
        "featured": False,
        "description": "Plaza principal del centro histórico de Colima, rodeada por portales y edificios representativos.",
        "schedule": "Todos los días · Espacio público",
        "lat": 19.2433584,
        "lng": -103.7285218,
        "location_note": "Centro, Colima, Colima",
        "tags": ["Cultura", "Centro histórico", "Familia"],
        "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/91/JardinLibertadColima1.jpg/1280px-JardinLibertadColima1.jpg",
        "source_data": "OpenStreetMap; Visita Colima",
        "image_credit_url": "https://commons.wikimedia.org/wiki/File:JardinLibertadColima1.jpg",
    },
    {
        "slug": "catedral-basilica-menor-colima",
        "name": "Catedral Basílica Menor de Colima",
        "type": "Turismo",
        "municipality": "Colima",
        "active": True,
        "featured": False,
        "description": "Catedral situada junto al Jardín Libertad y uno de los principales referentes arquitectónicos del centro de Colima.",
        "schedule": "Consultar antes de visitar · El acceso puede variar durante servicios religiosos",
        "lat": 19.243198,
        "lng": -103.72878,
        "location_note": "Reforma 21, Centro, Colima, Colima",
        "tags": ["Cultura", "Arquitectura", "Religioso"],
        "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ce/ColimaCathedral01.jpg/1280px-ColimaCathedral01.jpg",
        "source_data": "OpenStreetMap; Visita Colima",
        "image_credit_url": "https://commons.wikimedia.org/wiki/File:ColimaCathedral01.jpg",
    },
    {
        "slug": "palacio-gobierno-colima",
        "name": "Palacio de Gobierno de Colima",
        "type": "Turismo",
        "municipality": "Colima",
        "active": True,
        "featured": False,
        "description": "Edificio histórico frente al Jardín Libertad que forma parte del conjunto monumental del centro de Colima.",
        "schedule": "Consultar antes de visitar · Confirmar acceso a exposiciones o recorridos",
        "lat": 19.243045,
        "lng": -103.729118,
        "location_note": "Reforma 37, Centro, Colima, Colima",
        "tags": ["Cultura", "Historia", "Arquitectura"],
        "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/17/Palacio_de_Gobierno_Colima_2_noche_fiestas_patrias_2012.jpg/1280px-Palacio_de_Gobierno_Colima_2_noche_fiestas_patrias_2012.jpg",
        "source_data": "Sistema de Información Cultural; Gobierno de Colima",
        "image_credit_url": "https://commons.wikimedia.org/wiki/File:Palacio_de_Gobierno_Colima_2_noche_fiestas_patrias_2012.jpg",
    },
    {
        "slug": "zona-arqueologica-la-campana",
        "name": "Zona arqueológica La Campana",
        "type": "Turismo",
        "municipality": "Villa de Álvarez",
        "active": True,
        "featured": True,
        "description": "Antiguo asentamiento urbano del occidente mesoamericano con plazas, estructuras y petroglifos.",
        "schedule": "Consultar calendario oficial · Consultar horarios y tarifas vigentes del INAH",
        "lat": 19.268234,
        "lng": -103.725265,
        "location_note": "Acceso a la Zona Arqueológica, Villa de Álvarez, Colima",
        "tags": ["Arqueología", "Historia", "Cultura"],
        "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/58/Zona_Arqueol%C3%B3gica_de_%22La_Campana%22%2C_Colima%2C_Colima.JPG/1280px-Zona_Arqueol%C3%B3gica_de_%22La_Campana%22%2C_Colima%2C_Colima.JPG",
        "source_data": "INAH; OpenStreetMap",
        "image_credit_url": "https://commons.wikimedia.org/wiki/File:Zona_Arqueol%C3%B3gica_de_%22La_Campana%22,_Colima,_Colima.JPG",
    },
    {
        "slug": "zona-arqueologica-el-chanal",
        "name": "Zona arqueológica El Chanal",
        "type": "Turismo",
        "municipality": "Colima",
        "active": True,
        "featured": False,
        "description": "Sitio arqueológico del periodo Posclásico con templos, altares, plazas y una cancha para el juego de pelota.",
        "schedule": "Consultar calendario oficial · Consultar horarios y tarifas vigentes del INAH",
        "lat": 19.2931141,
        "lng": -103.7060212,
        "location_note": "Calle Teotihuacán, El Chanal, Colima",
        "tags": ["Arqueología", "Historia", "Cultura"],
        "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/57/Zona_Arqueol%C3%B3gica_de_El_Chanal_en_Colima%2C_M%C3%A9xico_%2815-01-2003%29.jpg/1280px-Zona_Arqueol%C3%B3gica_de_El_Chanal_en_Colima%2C_M%C3%A9xico_%2815-01-2003%29.jpg",
        "source_data": "INAH; OpenStreetMap",
        "image_credit_url": "https://commons.wikimedia.org/wiki/File:Zona_Arqueol%C3%B3gica_de_El_Chanal_en_Colima,_M%C3%A9xico_(15-01-2003).jpg",
    },
    {
        "slug": "parque-piedra-lisa",
        "name": "Parque de la Piedra Lisa",
        "type": "Turismo",
        "municipality": "Colima",
        "active": True,
        "featured": False,
        "description": "Parque tradicional de la ciudad conocido por su gran piedra volcánica pulida, utilizada como resbaladilla.",
        "schedule": "Todos los días · Espacio público; confirmar condiciones del parque",
        "lat": 19.2392892,
        "lng": -103.7142399,
        "location_note": "Parque de la Piedra Lisa, Colima, Colima",
        "tags": ["Familia", "Parque", "Tradición"],
        "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8b/PiedraLisa01.jpg/1280px-PiedraLisa01.jpg",
        "source_data": "OpenStreetMap; Visita Colima",
        "image_credit_url": "https://commons.wikimedia.org/wiki/File:PiedraLisa01.jpg",
    },
    {
        "slug": "playa-la-audiencia",
        "name": "Playa La Audiencia",
        "type": "Turismo",
        "municipality": "Manzanillo",
        "active": True,
        "featured": True,
        "description": "Pequeña bahía de Manzanillo conocida por sus aguas generalmente tranquilas y actividades recreativas.",
        "schedule": "Todos los días · Acceso sujeto a condiciones marítimas y locales",
        "lat": 19.1047001,
        "lng": -104.35014,
        "location_note": "Península de Santiago, Manzanillo, Colima",
        "tags": ["Playa", "Mar", "Familia"],
        "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/73/Playa_La_Audiencia.JPG/1280px-Playa_La_Audiencia.JPG",
        "source_data": "OpenStreetMap; Visita Colima",
        "image_credit_url": "https://commons.wikimedia.org/wiki/File:Playa_La_Audiencia.JPG",
    },
    {
        "slug": "playa-miramar",
        "name": "Playa Miramar",
        "type": "Turismo",
        "municipality": "Manzanillo",
        "active": True,
        "featured": False,
        "description": "Extensa playa de la bahía de Santiago, popular para caminar y disfrutar del paisaje del Pacífico.",
        "schedule": "Todos los días · Acceso sujeto a condiciones marítimas y locales",
        "lat": 19.1185177,
        "lng": -104.3861076,
        "location_note": "Boulevard Costero Miguel de la Madrid, Manzanillo, Colima",
        "tags": ["Playa", "Mar", "Atardecer"],
        "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4d/Manzanillo%2C_Mexico_-_panoramio.jpg/1280px-Manzanillo%2C_Mexico_-_panoramio.jpg",
        "source_data": "OpenStreetMap; Visita Colima",
        "image_credit_url": "https://commons.wikimedia.org/wiki/File:Manzanillo,_Mexico_-_panoramio.jpg",
    },
    {
        "slug": "playa-cuyutlan",
        "name": "Playa de Cuyutlán",
        "type": "Turismo",
        "municipality": "Armería",
        "active": True,
        "featured": False,
        "description": "Playa de arena oscura y oleaje fuerte junto a la localidad de Cuyutlán.",
        "schedule": "Todos los días · Precaución por oleaje; consultar condiciones marítimas",
        "lat": 18.918889,
        "lng": -104.069722,
        "location_note": "Cuyutlán, Armería, Colima",
        "tags": ["Playa", "Mar", "Naturaleza"],
        "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/20/Playa_de_Cuyutlan.JPG/1280px-Playa_de_Cuyutlan.JPG",
        "source_data": "OpenStreetMap; Visita Colima",
        "image_credit_url": "https://commons.wikimedia.org/wiki/File:Playa_de_Cuyutlan.JPG",
    },
    {
        "slug": "laguna-cuyutlan",
        "name": "Laguna de Cuyutlán",
        "type": "Turismo",
        "municipality": "Armería",
        "active": True,
        "featured": False,
        "description": "Sistema lagunar costero de gran importancia ecológica, con manglares y hábitat para aves residentes y migratorias.",
        "schedule": "Consultar recorridos disponibles · Confirmar acceso autorizado",
        "lat": 18.9522572,
        "lng": -104.0561209,
        "location_note": "Laguna de Cuyutlán, Colima. El marcador señala una referencia central, no una entrada específica.",
        "tags": ["Naturaleza", "Laguna", "Manglar", "Aves"],
        "image": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f0/Cuyutlan%2C_colima_._-_panoramio.jpg/1280px-Cuyutlan%2C_colima_._-_panoramio.jpg",
        "source_data": "OpenStreetMap; información turística de Colima",
        "image_credit_url": "https://commons.wikimedia.org/wiki/File:Cuyutlan,_colima_._-_panoramio.jpg",
    },
    {
        "slug": "cascada-el-salto-minatitlan",
        "name": "Cascada El Salto",
        "type": "Turismo",
        "municipality": "Minatitlán",
        "active": True,
        "featured": False,
        "description": "Cascada y paraje natural del municipio de Minatitlán, frecuentado por visitantes de la región.",
        "schedule": "Consultar antes de visitar · Confirmar acceso, clima y condiciones del camino",
        "lat": 19.3678102,
        "lng": -104.0874484,
        "location_note": "Carretera Manzanillo–Minatitlán, Minatitlán, Colima",
        "tags": ["Naturaleza", "Cascada", "Aventura"],
        "image": "https://upload.wikimedia.org/wikipedia/commons/d/d6/Cascada_de_El_Salto.jpg",
        "source_data": "OpenStreetMap; Visita Colima",
        "image_credit_url": "https://commons.wikimedia.org/wiki/File:Cascada_de_El_Salto.jpg",
    },
    {
        "slug": "monumento-pez-vela",
        "name": "Monumento al Pez Vela",
        "type": "Turismo",
        "municipality": "Manzanillo",
        "active": True,
        "featured": False,
        "description": "Escultura monumental de Sebastián situada en el centro histórico y convertida en uno de los símbolos de Manzanillo.",
        "schedule": "Todos los días · Espacio público",
        "lat": 19.054208,
        "lng": -104.3168094,
        "location_note": "Centro Histórico, Manzanillo, Colima",
        "tags": ["Cultura", "Escultura", "Centro histórico"],
        "image": "https://upload.wikimedia.org/wikipedia/commons/7/74/Montaje_de_Manzanillo.jpg",
        "source_data": "OpenStreetMap; información turística de Manzanillo",
        "image_credit_url": "https://commons.wikimedia.org/wiki/File:Montaje_de_Manzanillo.jpg",
    },
]
