# Ubicaciones contrastadas con OpenStreetMap (consulta puntual, sin llamadas en tiempo de ejecución):
# Comala https://www.openstreetmap.org/node/6537422367
# Suchitlán https://www.openstreetmap.org/node/10771309553 (punto de observación, no el cráter)
# La Boquita https://www.openstreetmap.org/node/7180011968
# Jardín Libertad https://www.openstreetmap.org/way/1159046017
# Laguna La María https://www.openstreetmap.org/way/293068155 (centro de la laguna)
# Museo https://www.openstreetmap.org/relation/15767585
# Mercado Constitución https://www.openstreetmap.org/node/5855554185
# Casa de la Cultura Comala https://www.openstreetmap.org/way/1192125485 (sede ilustrativa)
# Teatro Hidalgo https://www.openstreetmap.org/way/171809810 (sede ilustrativa)
# Tianguis de la Villa https://mx.maptons.com/p/9499466555 (verificar horario)
CONTENT = [
 {"slug":"comala-pueblo-magico","name":"Comala, pueblo mágico","type":"Turismo","municipality":"Comala","active":True,"featured":True,"description":"Calles blancas, portales y la atmósfera que inspiró a Juan Rulfo.","schedule":"Abierto todo el día","lat":19.3231443,"lng":-103.7582664,"tags":["Cultura","Pueblos mágicos"],"image":"https://unsplash.com/photos/a-street-lined-with-benches-and-buildings-under-a-blue-sky-wB84N1jrfiM?w=1000"},
 {"slug":"volcan-de-fuego","name":"Volcán de Fuego desde Suchitlán","type":"Turismo","municipality":"Comala","active":True,"featured":True,"description":"Observa el volcán desde Suchitlán. Este punto de referencia no ofrece acceso al cráter.","schedule":"Vista al aire libre · consulta avisos de Protección Civil","lat":19.3745585,"lng":-103.7087398,"location_note":"El marcador corresponde al centro de Suchitlán, no a un mirador específico ni al cráter. Comprueba el punto de observación y las condiciones locales antes de salir.","tags":["Naturaleza","Aventura"],"image":"https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1000"},
 {"slug":"playa-la-boquita","name":"Playa La Boquita","type":"Turismo","municipality":"Manzanillo","active":True,"featured":True,"description":"Bahía tranquila, gastronomía local y atardeceres frente al Pacífico.","schedule":"Abierto todo el día","lat":19.1060124,"lng":-104.3988620,"tags":["Playa","Gastronomía"],"image":"https://unsplash.com/photos/lifeguard-chair-on-sandy-beach-8Ug4F8iM8NQ?w=1000"},
 {"slug":"jardin-libertad","name":"Jardín Libertad","type":"Turismo","municipality":"Colima","active":True,"featured":False,"description":"El corazón del centro histórico de la ciudad de Colima.","schedule":"Abierto todo el día","lat":19.2433584,"lng":-103.7285218,"tags":["Cultura","Centro histórico"],"image":"https://images.unsplash.com/photo-1531058020387-3be344556be6?w=1000"},
 {"slug":"laguna-la-maria","name":"Laguna La María","type":"Turismo","municipality":"Comala","active":True,"featured":False,"description":"Un espacio natural para caminar, respirar y disfrutar el paisaje.","schedule":"Horario de acceso por confirmar","lat":19.4614450,"lng":-103.7095051,"location_note":"El punto señala el centro de la laguna, no la entrada al centro ecoturístico. Confirma el acceso antes de viajar.","tags":["Naturaleza"],"image":"https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=1000"},
 {"slug":"museo-regional-historia","name":"Museo Regional de Historia","type":"Turismo","municipality":"Colima","active":True,"featured":False,"description":"Conoce la historia y las expresiones culturales de la región.","schedule":"Horario de visita por confirmar","lat":19.2427547,"lng":-103.7289773,"tags":["Cultura","Museos"],"image":"https://images.unsplash.com/photo-1564399579883-451a5d44ec08?w=1000"},
 {"slug":"tianguis-villa-alvarez","name":"Tianguis de la Villa","type":"Tianguis","municipality":"Villa de Álvarez","active":True,"featured":False,"description":"Sabores, productos y encuentro comunitario en la avenida Josefa Ortiz de Domínguez.","schedule":"Domingos · horario por confirmar","lat":19.2668533,"lng":-103.7432098,"location_note":"El punto corresponde al tianguis registrado en la avenida Josefa Ortiz de Domínguez. Confirma que opere y su horario antes de visitarlo.","tags":["Compras","Gastronomía"],"image":"https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=1000"},
 {"slug":"tianguis-artesanal-comala","name":"Tianguis artesanal de Comala (demo)","type":"Tianguis","municipality":"Comala","active":True,"featured":False,"description":"Ejemplo de actividad artesanal de fechas variables; la sede del tianguis no está confirmada.","schedule":"Fechas variables · por confirmar","lat":19.3261439,"lng":-103.7554240,"location_note":"Contenido ilustrativo. El punto ubica la Casa de la Cultura de Comala como referencia, no una sede confirmada del tianguis.","tags":["Artesanías"],"image":"https://unsplash.com/photos/a-red-and-yellow-building-with-a-mountain-in-the-background-Isb0cPo39Rs?w=1000"},
 {"slug":"mercado-obregon","name":"Mercado Constitución","type":"Mercados","municipality":"Colima","active":True,"featured":False,"description":"Un recorrido por los sabores cotidianos de la capital.","schedule":"Horario de atención por confirmar","lat":19.2402448,"lng":-103.7298978,"tags":["Gastronomía","Compras"],"image":"https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=1000"},
 {"slug":"feria-cultura-colima","name":"Festival de Cultura Colima (demo)","type":"Eventos","municipality":"Colima","active":True,"featured":False,"description":"Ejemplo de evento cultural para demostrar los filtros; no existe cartelera confirmada.","schedule":"Fecha de ejemplo: 18 oct 2026 · 18:00","lat":19.2429725,"lng":-103.7297302,"location_note":"Evento ilustrativo. El punto muestra el Teatro Hidalgo como recinto de referencia; ni la sede ni la fecha están confirmadas para este festival.","tags":["Cultura","Familia"],"image":"https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1000"},
]
